name: SimpleRules
author: Junkdude
main: SimpleRules\Main
version: 2.5
api:
- 1.14.0
- 2.0.0
commands:
 rules:
  usage: /rules
  description: Shows A List Of Rules.
permissions:
 simplerules.rules:
  default: op
  description:
