---
rule#1: "Example"
rule#2: "Example"
rule#3: "Example"
rule#4: "Example"
rule#5: "Example"
rule#6: "Example"
rule#7: "Example"
rule#8: "Example"
rule#9: "Example"
rule#10: "Example"
...
